stages:
- name: Build
  steps:
  - runScriptConfig:
      image: php:7
      shellScript: |-
        make ci
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: agent-visy:${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
  when:
    branch:
      include:
      - master
notification: {}
